services:
  - type: web
    name: my-dash-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # No build command needed since you're using Docker
    startCommand: "/opt/venv/bin/python app.py"  # Start the app using the appropriate python path
    envVars:
      - key: FLASK_ENV
        value: production
